# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtDesigns/mass_rename_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from inspect import getmembers

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 640)
        MainWindow.setMinimumSize(QtCore.QSize(800, 640))
        MainWindow.setMaximumSize(QtCore.QSize(800, 640))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.led_input_path = QtWidgets.QLineEdit(self.centralwidget)
        self.led_input_path.setGeometry(QtCore.QRect(10, 10, 430, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_input_path.sizePolicy().hasHeightForWidth())
        self.led_input_path.setSizePolicy(sizePolicy)
        self.led_input_path.setMinimumSize(QtCore.QSize(430, 24))
        self.led_input_path.setMaximumSize(QtCore.QSize(430, 24))
        self.led_input_path.setObjectName("led_input_path")
        self.btn_main_dir_path_browse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_main_dir_path_browse.setGeometry(QtCore.QRect(460, 10, 80, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.btn_main_dir_path_browse.sizePolicy().hasHeightForWidth())
        self.btn_main_dir_path_browse.setSizePolicy(sizePolicy)
        self.btn_main_dir_path_browse.setMinimumSize(QtCore.QSize(80, 24))
        self.btn_main_dir_path_browse.setMaximumSize(QtCore.QSize(80, 24))
        self.btn_main_dir_path_browse.setObjectName("btn_main_dir_path_browse")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 430, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(430, 220))
        self.listWidget.setMaximumSize(QtCore.QSize(430, 220))
        self.listWidget.setObjectName("listWidget")
        self.frame_checkbox = QtWidgets.QFrame(self.centralwidget)
        self.frame_checkbox.setGeometry(QtCore.QRect(10, 290, 780, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_checkbox.sizePolicy().hasHeightForWidth())
        self.frame_checkbox.setSizePolicy(sizePolicy)
        self.frame_checkbox.setMinimumSize(QtCore.QSize(780, 300))
        self.frame_checkbox.setMaximumSize(QtCore.QSize(780, 300))
        self.frame_checkbox.setStyleSheet("background-color: rgb(246, 230, 255);")
        self.frame_checkbox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_checkbox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_checkbox.setObjectName("frame_checkbox")
        self.label_frame_chkbx = QtWidgets.QLabel(self.frame_checkbox)
        self.label_frame_chkbx.setGeometry(QtCore.QRect(320, 40, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_frame_chkbx.sizePolicy().hasHeightForWidth())
        self.label_frame_chkbx.setSizePolicy(sizePolicy)
        self.label_frame_chkbx.setMinimumSize(QtCore.QSize(150, 20))
        self.label_frame_chkbx.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono for Powerline")
        font.setPointSize(11)
        self.label_frame_chkbx.setFont(font)
        self.label_frame_chkbx.setObjectName("label_frame_chkbx")
        self.led_new_genres = QtWidgets.QLineEdit(self.frame_checkbox)
        self.led_new_genres.setGeometry(QtCore.QRect(10, 10, 760, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_new_genres.sizePolicy().hasHeightForWidth())
        self.led_new_genres.setSizePolicy(sizePolicy)
        self.led_new_genres.setMinimumSize(QtCore.QSize(760, 24))
        self.led_new_genres.setMaximumSize(QtCore.QSize(760, 24))
        self.led_new_genres.setObjectName("led_new_genres")
        self.widget = QtWidgets.QWidget(self.frame_checkbox)
        self.widget.setGeometry(QtCore.QRect(31, 60, 711, 231))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # Generates checkboxes 1-40
        for genre in range(1, 41):
            setattr(self,
                    name := f'cb_genre_{genre}',
                    QtWidgets.QCheckBox(self.widget),
                    )
            if (genre+7) % 8 == 0:  # Create vertical layout every 8 checkbox.
                setattr(self,
                        layout := f'verticalLayout_{(genre+7)//8}',
                        QtWidgets.QVBoxLayout(),
                        )
                for _ in getmembers(self):  # Find new layout in members.
                    if _[0] == layout:
                        layout = _[1]
                        self.horizontalLayout.addLayout(layout)
            for member in getmembers(self):  # find new checkbox in members.
                if member[0] == name:
                    sizePolicy = QtWidgets.QSizePolicy(
                        QtWidgets.QSizePolicy.Fixed,
                        QtWidgets.QSizePolicy.Fixed,
                        )
                    sizePolicy.setHorizontalStretch(0)
                    sizePolicy.setVerticalStretch(0)
                    sizePolicy.setHeightForWidth(
                        member[1].sizePolicy().hasHeightForWidth()
                        )
                    member[1].setSizePolicy(sizePolicy)
                    member[1].setMinimumSize(QtCore.QSize(120, 20))
                    member[1].setMaximumSize(QtCore.QSize(120, 20))
                    member[1].setObjectName(name)
                    layout.addWidget(member[1])
                    self.ch_bxs.append(member[1])

        self.btn_main_dir_scan = QtWidgets.QPushButton(self.centralwidget)
        self.btn_main_dir_scan.setGeometry(QtCore.QRect(560, 10, 80, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.btn_main_dir_scan.sizePolicy().hasHeightForWidth())
        self.btn_main_dir_scan.setSizePolicy(sizePolicy)
        self.btn_main_dir_scan.setMinimumSize(QtCore.QSize(80, 24))
        self.btn_main_dir_scan.setMaximumSize(QtCore.QSize(80, 24))
        self.btn_main_dir_scan.setObjectName("btn_main_dir_scan")
        self.led_new_name = QtWidgets.QLineEdit(self.centralwidget)
        self.led_new_name.setGeometry(QtCore.QRect(10, 600, 430, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_new_name.sizePolicy().hasHeightForWidth())
        self.led_new_name.setSizePolicy(sizePolicy)
        self.led_new_name.setMinimumSize(QtCore.QSize(430, 24))
        self.led_new_name.setMaximumSize(QtCore.QSize(430, 24))
        self.led_new_name.setObjectName("led_new_name")
        self.btn_process = QtWidgets.QPushButton(self.centralwidget)
        self.btn_process.setGeometry(QtCore.QRect(710, 600, 80, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.btn_process.sizePolicy().hasHeightForWidth())
        self.btn_process.setSizePolicy(sizePolicy)
        self.btn_process.setMinimumSize(QtCore.QSize(80, 24))
        self.btn_process.setMaximumSize(QtCore.QSize(80, 24))
        self.btn_process.setObjectName("btn_process")
        self.frame_external = QtWidgets.QFrame(self.centralwidget)
        self.frame_external.setGeometry(QtCore.QRect(460, 50, 330, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_external.sizePolicy().hasHeightForWidth())
        self.frame_external.setSizePolicy(sizePolicy)
        self.frame_external.setMinimumSize(QtCore.QSize(330, 220))
        self.frame_external.setMaximumSize(QtCore.QSize(330, 220))
        self.frame_external.setStyleSheet("background-color: rgb(230, 248, 255);")
        self.frame_external.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_external.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_external.setObjectName("frame_external")
        self.label_frame_external = QtWidgets.QLabel(self.frame_external)
        self.label_frame_external.setGeometry(QtCore.QRect(90, 10, 180, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_frame_external.sizePolicy().hasHeightForWidth())
        self.label_frame_external.setSizePolicy(sizePolicy)
        self.label_frame_external.setMinimumSize(QtCore.QSize(180, 20))
        self.label_frame_external.setMaximumSize(QtCore.QSize(180, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono for Powerline")
        font.setPointSize(11)
        self.label_frame_external.setFont(font)
        self.label_frame_external.setObjectName("label_frame_external")
        self.label_current_name = QtWidgets.QLabel(self.centralwidget)
        self.label_current_name.setGeometry(QtCore.QRect(450, 603, 240, 18))
        self.label_current_name.setMinimumSize(QtCore.QSize(240, 18))
        self.label_current_name.setMaximumSize(QtCore.QSize(240, 18))
        self.label_current_name.setObjectName("label_current_name")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.led_input_path.setPlaceholderText(_translate("MainWindow", "Path..."))
        self.btn_main_dir_path_browse.setText(_translate("MainWindow", "Browse"))
        self.label_frame_chkbx.setText(_translate("MainWindow", "Checkboxes zone"))
        self.led_new_genres.setPlaceholderText(_translate("MainWindow", "New genres..."))

        # Set text for every member starts with 'cb_genre_'
        for cb_genre in getmembers(self):
            if cb_genre[0].startswith('cb_genre_'):
                cb_genre[1].setText(_translate("MainWindow", "CheckBox"))

        self.btn_main_dir_scan.setText(_translate("MainWindow", "Scan"))
        self.led_new_name.setPlaceholderText(_translate("MainWindow", "New name..."))
        self.btn_process.setText(_translate("MainWindow", "Process"))
        self.label_frame_external.setText(_translate("MainWindow", "External sources?"))
        self.label_current_name.setText(_translate("MainWindow", "label_current_name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
